name: flutter_ebook_app
description: A Flutter app for eBooks

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.11
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  epub_viewer: ^0.1.8
  esys_flutter_share: ^1.0.2
  firebase_auth: ^0.18.1+1
  firebase_core: ^0.5.0
  firebase_performance: ^0.4.2
  flutter_icons: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.0.2
  get_it: ^5.0.1
  google_fonts: ^1.1.0
  http: ^0.12.2
  image_picker: ^0.6.7+22
  logger: ^0.9.4
  mime_type: ^0.2.7
  objectdb: ^1.0.7+1
  path_provider: ^1.4.0
  permission_handler: ^4.2.0+hotfix.1
  provider: ^4.0.1
  retrofit: ^1.3.4+1
  shared_preferences: ^0.5.10
  uuid: ^2.2.0
  xml2json: ^4.3.0
  photo_view: ^0.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  fluttericon: ^1.0.7
  retrofit_generator: ^1.4.1+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
